#!/usr/bin/env python3
"""Generate a VS Code settings snippet for hediet.vscode-drawio custom libraries.

This repository generates Diagrams.net (draw.io) custom library XML files under `output/`.
For local verification, the Draw.io Integration extension also supports referencing a
local XML file via the `file` property.

This script reads `output/index.json` and prints a copy-paste-ready JSON snippet.

Usage:
  /path/to/.venv/bin/python local-dev/generate_drawio_local_settings.py
  /path/to/.venv/bin/python local-dev/generate_drawio_local_settings.py --out local-dev/settings.snippet.json

Notes:
  - Run the generator first so `output/index.json` exists:
      /path/to/.venv/bin/python -m src.main
  - For WSL2 + VS Code (Windows), use UNC path format:
      \\wsl.localhost\<distro>\home\...
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path


def title_from_filename(stem: str) -> str:
    # e.g. "ai-and-machine-learning" -> "Ai And Machine Learning"
    return stem.replace("_", " ").replace("-", " ").title()


def wsl_unc_path(workspace_root: Path, relative_posix_path: str) -> str:
    """Convert workspace-relative path to WSL UNC path for Windows VS Code.
    
    Example:
      output/azure/compute.xml -> \\\\wsl.localhost\\Ubuntu-24.04\\home\\user\\project\\output\\azure\\compute.xml
    """
    distro = os.environ.get("WSL_DISTRO_NAME", "Ubuntu-24.04")
    abs_path = (workspace_root / relative_posix_path).resolve()
    posix_str = abs_path.as_posix()
    # UNC format: \\wsl.localhost\<distro>\<posix-path-without-leading-slash>
    return f"\\\\wsl.localhost\\{distro}{posix_str}"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate Draw.io customLibraries snippet using local XML files (WSL UNC path)."
    )
    parser.add_argument(
        "--index",
        type=Path,
        default=Path("output/index.json"),
        help="Path to output/index.json (generated by src/main.py)",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Optional output path to write the snippet JSON",
    )
    args = parser.parse_args()

    if not args.index.exists():
        raise SystemExit(
            f"Index file not found: {args.index}. Run the generator first (python -m src.main)."
        )

    # Workspace root is the parent of the script's grandparent (local-dev -> root)
    workspace_root = Path(__file__).resolve().parent.parent

    providers: dict = json.loads(args.index.read_text(encoding="utf-8"))

    libraries: list[dict[str, str]] = []
    for provider_id, meta in providers.items():
        provider_name = meta.get("name", provider_id)
        for rel_path in meta.get("categories", []):
            p = Path(rel_path)
            category_title = title_from_filename(p.stem)
            libraries.append(
                {
                    "entryId": f"{provider_id}:{p.stem}",
                    "libName": f"{provider_name} - {category_title}",
                    "file": wsl_unc_path(workspace_root, rel_path),
                }
            )

    snippet = {"hediet.vscode-drawio.customLibraries": libraries}
    text = json.dumps(snippet, ensure_ascii=False, indent=2) + "\n"

    if args.out is not None:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(text, encoding="utf-8")

    print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
